name: http_interop_http
description: Interop-compatible wrapper over the standard Dart http package
version: 0.8.1
repository: https://github.com/f3ath/dart-http-interop-http

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  http_interop: ^2.0.0
  http: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
  cider: ^0.2.4
  test: ^1.21.1
  check_coverage: ^0.0.2

cider:
  link_template:
    tag: 'https://github.com/f3ath/dart-http-interop-http/releases/tag/%tag%'
    diff: 'https://github.com/f3ath/dart-http-interop-http/compare/%from%...%to%'
